### ISSUE TITLE
about moderator registration

### ISSUE THREAD

**Issue by Markkos89** [zenbitETH/zengo#21]
- set the `isModeratorRegistrationOpen` to true when contract deploys
- create a function to turn that value to `false` when required only by Owner

- in the following screen the addresses with Owner roles will be able to "accept" moderators applications
![image](https://github.com/zenbitETH/zengo/assets/2791028/80d821d2-5c7e-40cb-a6b0-634044d3b375)

- if the address is NOT OWNER will be able to click on the "Registrarse" button and this modal will popup
![image](https://github.com/zenbitETH/zengo/assets/2791028/63262216-a8f9-4ff2-b723-52f3fcee6f9f)

**Comment by shyam-patel-kira** [comment]
I'm gonna try this one

**Comment by shyam-patel-kira** [comment]
Do we need this at all?
