### ISSUE TITLE
Review dependabot security warnings

### ISSUE THREAD

**Issue by Markkos89** [zenbitETH/zengo#26]
https://github.com/zenbitETH/zengo/security/dependabot 

![image](https://github.com/zenbitETH/zengo/assets/2791028/54ea0177-c664-4b4e-b844-57aa8a7d49f4)

thinking in the future users IMHO we cannot leave this without reviewing it, perhaps someone of you know how to handle this alerts? Or to which package are they related? 

:pray:

**Comment by HabacucMX** [comment]
Let's check this after migrating to the monorepo

**Comment by shyam-patel-kira** [comment]
Are these still there?

**Comment by Markkos89** [comment]
> Are these still there?

yes https://github.com/zenbitETH/zengo/security/dependabot

**Comment by shyam-patel-kira** [comment]
I suggest to remove the lock file from github and add it in .gitignore

**Comment by HabacucMX** [comment]
I attempted to address the vulnerabilities by running `pnpm audit fix` in the `fix/pnpm-dependeincies` branch, but this resulted in a failure during the Vercel deployment.

**Comment by HabacucMX** [comment]
@Markkos89 helped me track the dependencies issues, and we run the following updates to solve them:

` pnpm install @thirdweb-dev/chains@^0.1.47 --filter dapp;   `
`pnpm install -D @tailwindcss/forms@^0.5.5 @types/node@^20.5.4 --filter dapp`

Deploy on vercel work properly in the PR #45
