### ISSUE TITLE
Add required enums and update structs

### ISSUE THREAD

**Issue by shyam-patel-kira** [zenbitETH/zengo#59]

**Comment by HabacucMX** [comment]
@shyam-patel-kira please consider the following elements in the `moderatorsList` struct:

- Address
- Moderator type (there will be five categories that can be stored in an array)
```
Five moderator types:
0 - Civil organization 
1 - Private sector
2 - Academy
3 - Government
4 - Open
```
- Position (string)
- Organization (string)

**Comment by shyam-patel-kira** [comment]
Made a PR for this
