### ISSUE TITLE
Add getter functions

### ISSUE THREAD

**Issue by shyam-patel-kira** [zenbitETH/zengo#68]
Add getter functions for

- [x] Proposals
- [x] VotingIterations
- [x] Evidence
- [x] Moderators

**Comment by Markkos89** [comment]
> Add getter functions for
> 
> * [ ]  Proposals
> * [ ]  VotingIterations
> * [ ]  Evidence
> * [ ]  Moderators

It would be great if can have the list of `all proposals`  with their own `votingIterations` and `evidences` !

If you can think on a map being done in the frontend, that is exactly what you can do contract side to achieve this :raised_hands: 

Regards :muscle:

**Comment by shyam-patel-kira** [comment]
This is going to be a very heavy function
